version: '3.8'

services:
  db: 
    image: postgres

    restart: always

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - '5432:5432'

    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

    
  api:
    container_name: fyp-api
    build:
      context: ./

    depends_on:
      - db
    
    ports:
      - 4000:4000
    
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgress

    links:
      - db
    volumes:
      - './:/src'

volumes:
  db:
    driver: local